### ISSUE TITLE
Unclear how to obtain info for config file

### ISSUE THREAD

**Issue by Chewt** [yiqiaoli/foxwq-sgf-dl#1]
First off, nice project! I was looking for something like this just the other day, and I'm glad to see someone working on it.

You mention that you can obtain some of the info via the login api, but how do I do that? Do I need to open wireshark and watch the actual traffic? Or is there another way that works.

**Comment by yiqiaoli** [comment]
> First off, nice project! I was looking for something like this just the other day, and I'm glad to see someone working on it.
> 
> You mention that you can obtain some of the info via the login api, but how do I do that? Do I need to open wireshark and watch the actual traffic? Or is there another way that works.

Thanks for the feedback! 

So here is the swoop: when we access the APIs for game metadata and SGF records, we need three things: a token, a time_stamp, and a session. The token stays the same once you're logged in, but the timestamp and session were supposed to change with each call. Originally, I planned to get these from the login API and update them each time we made an API call. I guess the session is generated from the token and timestamp using an MD5 hash. Unfortunately, I haven’t fully decoded this yet. 

However, it seems that the server isn’t really checking the timestamp itself. Instead, it checks if the session, which comes from the timestamp and token, matches its calculations.

For now, our workaround is straightforward: monitor the network only once, capture these three values, put them in the config, and everything should run smoothly.

**Comment by Chewt** [comment]
I got it working now, thanks!

This is a very useful tool!

**Comment by mr5iff** [comment]
Thanks for creating this! How do you get `session` in the first place? (You mentioned monitoring network, may I know which client did you use?)

**Comment by Chewt** [comment]
It's been a while so I don't remember 100%, but I believe I used wireshark to capture network traffic while logging in with the regular fox client. From there I was able to get the session data. I will add that after a period of time my session data no longer worked and I had to do this process again.
